const mongoose = require("mongoose");
const Product = require("../models/Product");
require("dotenv").config();

const sampleProducts = [
  {
    id: 1,
    name: "חלב 3%",
    description: "חלב טרי 3% שומן, 1 ליטר",
    category: "מוצרי חלב",
    prices: {
      שופרסל: 5.9,
      "רמי לוי": 5.5,
      ויקטורי: 5.95,
      "יינות ביתן": 6.2,
    },
    unit: "ליטר",
    popularity: 95,
    rating: 4.7,
  },
  {
    id: 2,
    name: "לחם אחיד פרוס",
    description: "לחם אחיד פרוס, 750 גרם",
    category: "לחם ומאפים",
    prices: {
      שופרסל: 6.8,
      "רמי לוי": 5.9,
      ויקטורי: 6.5,
      "יינות ביתן": 6.9,
    },
    unit: "יחידה",
    popularity: 90,
    rating: 4.2,
  },
  {
    id: 3,
    name: "ביצים L",
    description: "מארז 12 ביצים גודל L",
    category: "ביצים ומוצרי חלב",
    prices: {
      שופרסל: 12.9,
      "רמי לוי": 11.9,
      ויקטורי: 12.5,
      "יינות ביתן": 13.2,
    },
    unit: "מארז",
    popularity: 88,
    rating: 4.8,
  },
  {
    id: 4,
    name: "עגבניות",
    description: "עגבניות טריות",
    category: "ירקות ופירות",
    prices: {
      שופרסל: 7.9,
      "רמי לוי": 6.9,
      ויקטורי: 7.5,
      "יינות ביתן": 8.2,
    },
    unit: "ק״ג",
    popularity: 85,
    rating: 4.5,
  },
  {
    id: 5,
    name: "מלפפונים",
    description: "מלפפונים טריים",
    category: "ירקות ופירות",
    prices: {
      שופרסל: 6.9,
      "רמי לוי": 5.9,
      ויקטורי: 6.5,
      "יינות ביתן": 7.2,
    },
    unit: "ק״ג",
    popularity: 84,
    rating: 4.4,
  },
  {
    id: 6,
    name: "פסטה ברילה",
    description: "פסטה ברילה ספגטי מס׳ 5, 500 גרם",
    category: "מזון יבש",
    prices: {
      שופרסל: 8.9,
      "רמי לוי": 7.9,
      ויקטורי: 8.5,
      "יינות ביתן": 9.2,
    },
    unit: "יחידה",
    popularity: 75,
    rating: 4.6,
  },
  {
    id: 7,
    name: "אורז בסמטי",
    description: "אורז בסמטי פרימיום, 1 ק״ג",
    category: "מזון יבש",
    prices: {
      שופרסל: 16.9,
      "רמי לוי": 14.9,
      ויקטורי: 16.5,
      "יינות ביתן": 17.9,
    },
    unit: "ק״ג",
    popularity: 70,
    rating: 4.5,
  },
  {
    id: 8,
    name: "טונה בשמן קנולה",
    description: "טונה בשמן קנולה, 4 יחידות",
    category: "שימורים",
    prices: {
      שופרסל: 19.9,
      "רמי לוי": 17.9,
      ויקטורי: 19.5,
      "יינות ביתן": 21.9,
    },
    unit: "מארז",
    popularity: 68,
    rating: 4.3,
  },
  {
    id: 9,
    name: "קוקה קולה",
    description: "קוקה קולה, 6 פחיות",
    category: "משקאות",
    prices: {
      שופרסל: 18.9,
      "רמי לוי": 16.9,
      ויקטורי: 17.9,
      "יינות ביתן": 19.9,
    },
    unit: "מארז",
    popularity: 82,
    rating: 4.7,
  },
  {
    id: 10,
    name: "שמן זית כתית",
    description: "שמן זית כתית מעולה, 750 מ״ל",
    category: "שמנים ורטבים",
    prices: {
      שופרסל: 29.9,
      "רמי לוי": 26.9,
      ויקטורי: 28.9,
      "יינות ביתן": 32.9,
    },
    unit: "בקבוק",
    popularity: 65,
    rating: 4.8,
  },
  {
    id: 11,
    name: "קפה טורקי עלית",
    description: "קפה טורקי עלית, 200 גרם",
    category: "קפה ותה",
    prices: {
      שופרסל: 12.9,
      "רמי לוי": 10.9,
      ויקטורי: 11.9,
      "יינות ביתן": 13.9,
    },
    unit: "יחידה",
    popularity: 72,
    rating: 4.6,
  },
  {
    id: 12,
    name: "תפוזים",
    description: "תפוזים טריים",
    category: "ירקות ופירות",
    prices: {
      שופרסל: 8.9,
      "רמי לוי": 7.9,
      ויקטורי: 8.5,
      "יינות ביתן": 9.2,
    },
    unit: "ק״ג",
    popularity: 78,
    rating: 4.5,
  },
  {
    id: 13,
    name: "בננות",
    description: "בננות טריות",
    category: "פירות וירקות",
    prices: {
      שופרסל: 7.9,
      "רמי לוי": 7.5,
      ויקטורי: 7.8,
      "יינות ביתן": 8.0,
    },
    unit: "ק״ג",
    popularity: 80,
    rating: 4.7,
  },
  {
    id: 14,
    name: "בצל",
    description: "בצל טרי",
    category: "פירות וירקות",
    prices: {
      שופרסל: 3.9,
      "רמי לוי": 3.5,
      ויקטורי: 3.8,
      "יינות ביתן": 4.0,
    },
    unit: "ק״ג",
    popularity: 75,
    rating: 4.4,
  },
  {
    id: 15,
    name: "שום",
    description: "שום טרי",
    category: "פירות וירקות",
    prices: {
      שופרסל: 9.9,
      "רמי לוי": 8.5,
      ויקטורי: 9.0,
      "יינות ביתן": 9.8,
    },
    unit: "ק״ג",
    popularity: 68,
    rating: 4.6,
  },
  {
    id: 16,
    name: "קיווי",
    description: "קיווי טרי",
    category: "פירות וירקות",
    prices: {
      שופרסל: 14.9,
      "רמי לוי": 13.5,
      ויקטורי: 14.0,
      "יינות ביתן": 15.2,
    },
    unit: "ק״ג",
    popularity: 85,
    rating: 4.5,
  },
  {
    id: 17,
    name: "פאפיה",
    description: "פאפיה טריה",
    category: "פירות וירקות",
    prices: {
      שופרסל: 10.5,
      "רמי לוי": 9.8,
      ויקטורי: 10.2,
      "יינות ביתן": 10.9,
    },
    unit: "ק״ג",
    popularity: 70,
    rating: 4.3,
  },
  {
    id: 18,
    name: "אבטיח",
    description: "אבטיח טרי",
    category: "פירות וירקות",
    prices: {
      שופרסל: 12.9,
      "רמי לוי": 11.9,
      ויקטורי: 12.5,
      "יינות ביתן": 13.3,
    },
    unit: "ק״ג",
    popularity: 85,
    rating: 4.7,
  },
  {
    id: 19,
    name: "אננס",
    description: "אננס טרי",
    category: "פירות וירקות",
    prices: {
      שופרסל: 18.9,
      "רמי לוי": 17.0,
      ויקטורי: 17.8,
      "יינות ביתן": 19.2,
    },
    unit: "ק״ג",
    popularity: 73,
    rating: 4.4,
  },
  {
    id: 20,
    name: "תפוחים",
    description: "תפוחים טריים",
    category: "פירות וירקות",
    prices: {
      שופרסל: 9.5,
      "רמי לוי": 8.9,
      ויקטורי: 9.2,
      "יינות ביתן": 9.8,
    },
    unit: "ק״ג",
    popularity: 80,
    rating: 4.6,
  },
  {
    id: 21,
    name: "פול קפוא",
    description: "פול קפוא, 400 גרם",
    category: "קפואים",
    prices: {
      שופרסל: 5.9,
      "רמי לוי": 5.4,
      ויקטורי: 5.6,
      "יינות ביתן": 6.0,
    },
    unit: "חבילה",
    popularity: 65,
    rating: 4.4,
  },
  {
    id: 22,
    name: "ברוקולי קפוא",
    description: "ברוקולי קפוא, 500 גרם",
    category: "קפואים",
    prices: {
      שופרסל: 8.9,
      "רמי לוי": 8.5,
      ויקטורי: 8.6,
      "יינות ביתן": 9.0,
    },
    unit: "חבילה",
    popularity: 72,
    rating: 4.5,
  },
  {
    id: 23,
    name: "סרדינים בשמן זית",
    description: "סרדינים בשמן זית, 200 גרם",
    category: "שימורים",
    prices: {
      שופרסל: 7.5,
      "רמי לוי": 6.8,
      ויקטורי: 7.0,
      "יינות ביתן": 7.5,
    },
    unit: "חבילה",
    popularity: 80,
    rating: 4.6,
  },
  {
    id: 24,
    name: "פלאפל מוכן",
    description: "פלאפל מוכן, 400 גרם",
    category: "מזון מוכן",
    prices: {
      שופרסל: 15.9,
      "רמי לוי": 14.9,
      ויקטורי: 15.2,
      "יינות ביתן": 15.8,
    },
    unit: "חבילה",
    popularity: 90,
    rating: 4.7,
  },
  {
    id: 25,
    name: "בורגר צמחי",
    description: "בורגר צמחי, 250 גרם",
    category: "מזון מוכן",
    prices: {
      שופרסל: 14.5,
      "רמי לוי": 13.9,
      ויקטורי: 14.1,
      "יינות ביתן": 14.6,
    },
    unit: "חבילה",
    popularity: 85,
    rating: 4.4,
  },
  {
    id: 26,
    name: "אורז יסמין",
    description: "אורז יסמין, 1 ק״ג",
    category: "מזון יבש",
    prices: {
      שופרסל: 12.9,
      "רמי לוי": 11.8,
      ויקטורי: 12.5,
      "יינות ביתן": 13.0,
    },
    unit: "ק״ג",
    popularity: 82,
    rating: 4.6,
  },
  {
    id: 27,
    name: "טחינה גולמית",
    description: "טחינה גולמית, 400 גרם",
    category: "תבלינים",
    prices: {
      שופרסל: 10.9,
      "רמי לוי": 9.8,
      ויקטורי: 10.5,
      "יינות ביתן": 11.0,
    },
    unit: "חבילה",
    popularity: 77,
    rating: 4.7,
  },
  {
    id: 28,
    name: "קטשופ",
    description: "קטשופ, 500 גרם",
    category: "תבלינים",
    prices: {
      שופרסל: 7.5,
      "רמי לוי": 6.9,
      ויקטורי: 7.1,
      "יינות ביתן": 7.8,
    },
    unit: "חבילה",
    popularity: 80,
    rating: 4.4,
  },
  {
    id: 29,
    name: "ממרח שוקולד",
    description: "ממרח שוקולד, 350 גרם",
    category: "ממרחים",
    prices: {
      שופרסל: 15.9,
      "רמי לוי": 14.5,
      ויקטורי: 15.0,
      "יינות ביתן": 16.2,
    },
    unit: "חבילה",
    popularity: 85,
    rating: 4.8,
  },
  {
    id: 30,
    name: "רסק עגבניות",
    description: "רסק עגבניות, 500 גרם",
    category: "שימורים",
    prices: {
      שופרסל: 4.9,
      "רמי לוי": 4.3,
      ויקטורי: 4.5,
      "יינות ביתן": 4.8,
    },
    unit: "חבילה",
    popularity: 75,
    rating: 4.5,
  },
  {
    id: 31,
    name: "סודה לשתייה",
    description: "סודה לשתייה, 1 ליטר",
    category: "משקאות",
    prices: {
      שופרסל: 2.9,
      "רמי לוי": 2.5,
      ויקטורי: 2.7,
      "יינות ביתן": 2.9,
    },
    unit: "ליטר",
    popularity: 85,
    rating: 4.6,
  },
  {
    id: 32,
    name: "חומוס",
    description: "חומוס מוכן, 400 גרם",
    category: "מזון מוכן",
    prices: {
      שופרסל: 7.8,
      "רמי לוי": 6.9,
      ויקטורי: 7.2,
      "יינות ביתן": 7.5,
    },
    unit: "חבילה",
    popularity: 78,
    rating: 4.7,
  },
  {
    id: 33,
    name: "פלאפל",
    description: "פלאפל מוכן, 500 גרם",
    category: "מזון מוכן",
    prices: {
      שופרסל: 8.9,
      "רמי לוי": 7.8,
      ויקטורי: 8.5,
      "יינות ביתן": 9.0,
    },
    unit: "חבילה",
    popularity: 70,
    rating: 4.6,
  },
  {
    id: 34,
    name: "חלב סויה",
    description: "חלב סויה בטעם טבעי, 1 ליטר",
    category: "מוצרי חלב",
    prices: {
      שופרסל: 7.5,
      "רמי לוי": 6.9,
      ויקטורי: 7.1,
      "יינות ביתן": 7.8,
    },
    unit: "ליטר",
    popularity: 60,
    rating: 4.3,
  },
  {
    id: 35,
    name: "מיץ תפוזים",
    description: "מיץ תפוזים טבעי, 1 ליטר",
    category: "משקאות",
    prices: {
      שופרסל: 9.9,
      "רמי לוי": 9.5,
      ויקטורי: 9.8,
      "יינות ביתן": 10.0,
    },
    unit: "ליטר",
    popularity: 88,
    rating: 4.7,
  },
  {
    id: 36,
    name: "קפה נספרסו",
    description: "קפה נספרסו, 10 קפסולות",
    category: "קפה ותה",
    prices: {
      שופרסל: 24.9,
      "רמי לוי": 23.5,
      ויקטורי: 24.0,
      "יינות ביתן": 25.5,
    },
    unit: "חבילה",
    popularity: 90,
    rating: 4.9,
  },
  {
    id: 37,
    name: "סוכר",
    description: "סוכר לבן, 1 ק״ג",
    category: "מזון יבש",
    prices: {
      שופרסל: 4.9,
      "רמי לוי": 4.5,
      ויקטורי: 4.7,
      "יינות ביתן": 5.0,
    },
    unit: "ק״ג",
    popularity: 80,
    rating: 4.5,
  },
  {
    id: 38,
    name: "קמח לבן",
    description: "קמח לבן, 1 ק״ג",
    category: "מזון יבש",
    prices: {
      שופרסל: 3.8,
      "רמי לוי": 3.4,
      ויקטורי: 3.6,
      "יינות ביתן": 3.9,
    },
    unit: "ק״ג",
    popularity: 85,
    rating: 4.6,
  },
  {
    id: 39,
    name: "פיצוחים",
    description: "פיצוחים שונים, 200 גרם",
    category: "חטיפים",
    prices: {
      שופרסל: 12.9,
      "רמי לוי": 11.8,
      ויקטורי: 12.2,
      "יינות ביתן": 13.0,
    },
    unit: "חבילה",
    popularity: 78,
    rating: 4.7,
  },
  {
    id: 40,
    name: "בורגר עוף",
    description: "בורגר עוף, 300 גרם",
    category: "מזון מוכן",
    prices: {
      שופרסל: 15.9,
      "רמי לוי": 14.8,
      ויקטורי: 15.2,
      "יינות ביתן": 15.5,
    },
    unit: "חבילה",
    popularity: 80,
    rating: 4.6,
  },
  {
    id: 41,
    name: "דג סלמון קפוא",
    description: "דג סלמון קפוא, 500 גרם",
    category: "קפואים",
    prices: {
      שופרסל: 29.9,
      "רמי לוי": 28.5,
      ויקטורי: 29.0,
      "יינות ביתן": 30.5,
    },
    unit: "חבילה",
    popularity: 70,
    rating: 4.8,
  },
  {
    id: 42,
    name: "פיצה משפחתית",
    description: "פיצה משפחתית, 500 גרם",
    category: "מזון מוכן",
    prices: {
      שופרסל: 18.9,
      "רמי לוי": 17.9,
      ויקטורי: 18.5,
      "יינות ביתן": 19.0,
    },
    unit: "יחידה",
    popularity: 82,
    rating: 4.7,
  },
  {
    id: 43,
    name: "סרדינים",
    description: "סרדינים בשמן, 300 גרם",
    category: "שימורים",
    prices: {
      שופרסל: 7.5,
      "רמי לוי": 6.8,
      ויקטורי: 7.0,
      "יינות ביתן": 7.2,
    },
    unit: "חבילה",
    popularity: 75,
    rating: 4.5,
  },
  {
    id: 44,
    name: "צ'יפס פריז",
    description: "צ'יפס פריז, 1 קילוגרם",
    category: "קפואים",
    prices: {
      שופרסל: 12.5,
      "רמי לוי": 11.2,
      ויקטורי: 11.8,
      "יינות ביתן": 12.1,
    },
    unit: "ק״ג",
    popularity: 80,
    rating: 4.6,
  },
  {
    id: 45,
    name: "חזה עוף",
    description: "חזה עוף טרי, 500 גרם",
    category: "בשרים",
    prices: {
      שופרסל: 24.9,
      "רמי לוי": 22.5,
      ויקטורי: 23.8,
      "יינות ביתן": 25.0,
    },
    unit: "חבילה",
    popularity: 85,
    rating: 4.7,
  },
  {
    id: 46,
    name: "סטייק אנטריקוט",
    description: "סטייק אנטריקוט, 400 גרם",
    category: "בשרים",
    prices: {
      שופרסל: 35.9,
      "רמי לוי": 34.0,
      ויקטורי: 34.5,
      "יינות ביתן": 36.0,
    },
    unit: "חבילה",
    popularity: 80,
    rating: 4.8,
  },
  {
    id: 47,
    name: "קבנוס",
    description: "קבנוס, 200 גרם",
    category: "בשרים",
    prices: {
      שופרסל: 14.5,
      "רמי לוי": 13.8,
      ויקטורי: 14.2,
      "יינות ביתן": 14.7,
    },
    unit: "חבילה",
    popularity: 70,
    rating: 4.6,
  },
  {
    id: 48,
    name: "קוטג' 5%",
    description: "גבינת קוטג' 5%, 250 גרם",
    category: "מוצרי חלב",
    prices: {
      שופרסל: 5.2,
      "רמי לוי": 4.9,
      ויקטורי: 5.0,
      "יינות ביתן": 5.5,
    },
    unit: "חבילה",
    popularity: 88,
    rating: 4.8,
  },
  {
    id: 49,
    name: "שמנת מתוקה",
    description: "שמנת מתוקה 38%, 250 מ״ל",
    category: "מוצרי חלב",
    prices: {
      שופרסל: 7.5,
      "רמי לוי": 7.0,
      ויקטורי: 7.2,
      "יינות ביתן": 7.8,
    },
    unit: "חבילה",
    popularity: 80,
    rating: 4.7,
  },
  {
    id: 50,
    name: "יוגורט טבעי",
    description: "יוגורט טבעי, 200 גרם",
    category: "מוצרי חלב",
    prices: {
      שופרסל: 4.9,
      "רמי לוי": 4.5,
      ויקטורי: 4.8,
      "יינות ביתן": 5.0,
    },
    unit: "חבילה",
    popularity: 75,
    rating: 4.5,
  },
  {
    id: 51,
    name: "פשטידת ירק",
    description: "פשטידת ירק מוכנה, 300 גרם",
    category: "מזון מוכן",
    prices: {
      שופרסל: 12.9,
      "רמי לוי": 11.5,
      ויקטורי: 12.0,
      "יינות ביתן": 12.8,
    },
    unit: "חבילה",
    popularity: 70,
    rating: 4.6,
  },
  {
    id: 52,
    name: "מסטיקים",
    description: "מסטיקים בטעמים שונים, 100 גרם",
    category: "חטיפים",
    prices: {
      שופרסל: 5.9,
      "רמי לוי": 5.2,
      ויקטורי: 5.5,
      "יינות ביתן": 5.8,
    },
    unit: "חבילה",
    popularity: 85,
    rating: 4.7,
  },
  {
    id: 53,
    name: "שוקולית",
    description: "שוקולית לילדים, 300 גרם",
    category: "חטיפים",
    prices: {
      שופרסל: 9.5,
      "רמי לוי": 8.9,
      ויקטורי: 9.2,
      "יינות ביתן": 9.5,
    },
    unit: "חבילה",
    popularity: 70,
    rating: 4.5,
  },
  {
    id: 54,
    name: "פחית קולה",
    description: "פחית קולה, 330 מ״ל",
    category: "משקאות",
    prices: {
      שופרסל: 4.5,
      "רמי לוי": 4.0,
      ויקטורי: 4.2,
      "יינות ביתן": 4.5,
    },
    unit: "פחית",
    popularity: 95,
    rating: 4.6,
  },
  {
    id: 55,
    name: "מים מינרליים",
    description: "מים מינרליים, 1.5 ליטר",
    category: "משקאות",
    prices: {
      שופרסל: 3.2,
      "רמי לוי": 3.0,
      ויקטורי: 3.1,
      "יינות ביתן": 3.5,
    },
    unit: "ליטר",
    popularity: 90,
    rating: 4.7,
  },
  {
    id: 56,
    name: "חומוס תעשייתי",
    description: "חומוס תעשייתי, 400 גרם",
    category: "מזון מוכן",
    prices: {
      שופרסל: 6.5,
      "רמי לוי": 6.0,
      ויקטורי: 6.2,
      "יינות ביתן": 6.5,
    },
    unit: "חבילה",
    popularity: 78,
    rating: 4.4,
  },
  {
    id: 57,
    name: "אורז לבן",
    description: "אורז לבן, 1 ק״ג",
    category: "מזון יבש",
    prices: {
      שופרסל: 7.9,
      "רמי לוי": 7.2,
      ויקטורי: 7.5,
      "יינות ביתן": 7.8,
    },
    unit: "ק״ג",
    popularity: 85,
    rating: 4.6,
  },
  {
    id: 58,
    name: "פסטה מקמח חצי מלא",
    description: "פסטה מקמח חצי מלא, 500 גרם",
    category: "מזון יבש",
    prices: {
      שופרסל: 9.0,
      "רמי לוי": 8.5,
      ויקטורי: 8.8,
      "יינות ביתן": 9.3,
    },
    unit: "חבילה",
    popularity: 70,
    rating: 4.5,
  },
  {
    id: 59,
    name: "חומוס בולגרי",
    description: "חומוס בולגרי, 200 גרם",
    category: "מוצרי חלב",
    prices: {
      שופרסל: 8.5,
      "רמי לוי": 7.9,
      ויקטורי: 8.1,
      "יינות ביתן": 8.4,
    },
    unit: "חבילה",
    popularity: 80,
    rating: 4.6,
  },
  {
    id: 60,
    name: "אבקת סוכר",
    description: "אבקת סוכר, 250 גרם",
    category: "תבלינים",
    prices: {
      שופרסל: 6.2,
      "רמי לוי": 5.9,
      ויקטורי: 6.1,
      "יינות ביתן": 6.3,
    },
    unit: "חבילה",
    popularity: 72,
    rating: 4.5,
  },
  {
    id: 61,
    name: "שוקולד חלב",
    description: "שוקולד חלב, 100 גרם",
    category: "חטיפים",
    prices: {
      שופרסל: 5.5,
      "רמי לוי": 5.2,
      ויקטורי: 5.4,
      "יינות ביתן": 5.8,
    },
    unit: "חבילה",
    popularity: 85,
    rating: 4.6,
  },
  {
    id: 62,
    name: "צ'יפס שמנת ובצל",
    description: "צ'יפס שמנת ובצל, 200 גרם",
    category: "חטיפים",
    prices: {
      שופרסל: 7.5,
      "רמי לוי": 6.8,
      ויקטורי: 7.0,
      "יינות ביתן": 7.2,
    },
    unit: "חבילה",
    popularity: 75,
    rating: 4.4,
  },
  {
    id: 63,
    name: "חטיף טוויקס",
    description: "חטיף טוויקס, 50 גרם",
    category: "חטיפים",
    prices: {
      שופרסל: 3.5,
      "רמי לוי": 3.2,
      ויקטורי: 3.4,
      "יינות ביתן": 3.6,
    },
    unit: "חבילה",
    popularity: 85,
    rating: 4.6,
  },
  {
    id: 64,
    name: "שוקולד מריר 85%",
    description: "שוקולד מריר 85%, 100 גרם",
    category: "חטיפים",
    prices: {
      שופרסל: 7.9,
      "רמי לוי": 7.5,
      ויקטורי: 7.7,
      "יינות ביתן": 8.0,
    },
    unit: "חבילה",
    popularity: 78,
    rating: 4.8,
  },
  {
    id: 65,
    name: "פחית שימורי תירס",
    description: "פחית שימורי תירס, 400 גרם",
    category: "שימורים",
    prices: {
      שופרסל: 5.2,
      "רמי לוי": 4.8,
      ויקטורי: 5.0,
      "יינות ביתן": 5.4,
    },
    unit: "פחית",
    popularity: 70,
    rating: 4.5,
  },
  {
    id: 66,
    name: "קינואה",
    description: "קינואה, 500 גרם",
    category: "מזון יבש",
    prices: {
      שופרסל: 19.9,
      "רמי לוי": 18.5,
      ויקטורי: 19.0,
      "יינות ביתן": 19.9,
    },
    unit: "חבילה",
    popularity: 60,
    rating: 4.7,
  },
  {
    id: 67,
    name: "קפה גוליון",
    description: "קפה גוליון, 100 גרם",
    category: "קפה ותה",
    prices: {
      שופרסל: 10.9,
      "רמי לוי": 9.9,
      ויקטורי: 10.3,
      "יינות ביתן": 10.7,
    },
    unit: "חבילה",
    popularity: 78,
    rating: 4.7,
  },
  {
    id: 68,
    name: "תה ירוק",
    description: "תה ירוק, 25 שקיקים",
    category: "קפה ותה",
    prices: {
      שופרסל: 8.0,
      "רמי לוי": 7.5,
      ויקטורי: 7.8,
      "יינות ביתן": 8.2,
    },
    unit: "חבילה",
    popularity: 85,
    rating: 4.6,
  },
  {
    id: 69,
    name: "שמן קנולה",
    description: "שמן קנולה, 1 ליטר",
    category: "שמנים ורטבים",
    prices: {
      שופרסל: 10.9,
      "רמי לוי": 9.5,
      ויקטורי: 9.8,
      "יינות ביתן": 10.2,
    },
    unit: "ליטר",
    popularity: 85,
    rating: 4.6,
  },
  {
    id: 70,
    name: "חומוס מסחנה",
    description: "חומוס מסחנה, 400 גרם",
    category: "מזון מוכן",
    prices: {
      שופרסל: 8.8,
      "רמי לוי": 8.2,
      ויקטורי: 8.5,
      "יינות ביתן": 8.9,
    },
    unit: "חבילה",
    popularity: 75,
    rating: 4.5,
  },
  {
    id: 71,
    name: "שוקולד פרה",
    description: "שוקולד פרה, 100 גרם",
    category: "חטיפים",
    prices: {
      שופרסל: 6.5,
      "רמי לוי": 6.2,
      ויקטורי: 6.3,
      "יינות ביתן": 6.7,
    },
    unit: "חבילה",
    popularity: 78,
    rating: 4.7,
  },
  {
    id: 72,
    name: "פיצה אישית",
    description: "פיצה אישית, 250 גרם",
    category: "מזון מוכן",
    prices: {
      שופרסל: 12.9,
      "רמי לוי": 12.2,
      ויקטורי: 12.5,
      "יינות ביתן": 13.0,
    },
    unit: "יחידה",
    popularity: 85,
    rating: 4.7,
  },
  {
    id: 73,
    name: "קוטג' 9%",
    description: "גבינת קוטג' 9%, 250 גרם",
    category: "מוצרי חלב",
    prices: {
      שופרסל: 5.4,
      "רמי לוי": 5.0,
      ויקטורי: 5.3,
      "יינות ביתן": 5.7,
    },
    unit: "חבילה",
    popularity: 80,
    rating: 4.8,
  },
  {
    id: 74,
    name: "ממרח חמאת בוטנים",
    description: "ממרח חמאת בוטנים, 300 גרם",
    category: "ממרחים",
    prices: {
      שופרסל: 9.0,
      "רמי לוי": 8.5,
      ויקטורי: 8.8,
      "יינות ביתן": 9.2,
    },
    unit: "חבילה",
    popularity: 78,
    rating: 4.6,
  },
  {
    id: 75,
    name: "קוטג' 5%",
    description: "גבינת קוטג' 5%, 500 גרם",
    category: "מוצרי חלב",
    prices: {
      שופרסל: 9.5,
      "רמי לוי": 9.0,
      ויקטורי: 9.3,
      "יינות ביתן": 9.8,
    },
    unit: "חבילה",
    popularity: 85,
    rating: 4.7,
  },
  {
    id: 76,
    name: "אורז מלא",
    description: "אורז מלא, 1 ק״ג",
    category: "מזון יבש",
    prices: {
      שופרסל: 10.5,
      "רמי לוי": 9.9,
      ויקטורי: 10.2,
      "יינות ביתן": 10.6,
    },
    unit: "ק״ג",
    popularity: 78,
    rating: 4.6,
  },
  {
    id: 77,
    name: "קציצות עוף",
    description: "קציצות עוף מוכנות, 400 גרם",
    category: "מזון מוכן",
    prices: {
      שופרסל: 18.9,
      "רמי לוי": 17.5,
      ויקטורי: 18.0,
      "יינות ביתן": 18.8,
    },
    unit: "חבילה",
    popularity: 80,
    rating: 4.7,
  },
  {
    id: 78,
    name: "חומוס ביתי",
    description: "חומוס ביתי, 500 גרם",
    category: "מזון מוכן",
    prices: {
      שופרסל: 9.9,
      "רמי לוי": 9.5,
      ויקטורי: 9.8,
      "יינות ביתן": 10.2,
    },
    unit: "חבילה",
    popularity: 85,
    rating: 4.6,
  },
  {
    id: 79,
    name: "קולה דיאט",
    description: "קולה דיאט, 1.5 ליטר",
    category: "משקאות",
    prices: {
      שופרסל: 7.0,
      "רמי לוי": 6.5,
      ויקטורי: 6.8,
      "יינות ביתן": 7.2,
    },
    unit: "ליטר",
    popularity: 70,
    rating: 4.5,
  },
  {
    id: 80,
    name: "מים מינרליים",
    description: "מים מינרליים, 6 ליטר",
    category: "משקאות",
    prices: {
      שופרסל: 11.5,
      "רמי לוי": 10.9,
      ויקטורי: 11.2,
      "יינות ביתן": 11.5,
    },
    unit: "ליטר",
    popularity: 75,
    rating: 4.6,
  },
  {
    id: 81,
    name: "אפרסמון",
    description: "אפרסמון טרי",
    category: "פירות וירקות",
    prices: {
      שופרסל: 14.9,
      "רמי לוי": 13.8,
      ויקטורי: 14.2,
      "יינות ביתן": 14.9,
    },
    unit: "ק״ג",
    popularity: 70,
    rating: 4.7,
  },
  {
    id: 82,
    name: "תפוחי אדמה",
    description: "תפוחי אדמה, 1 ק״ג",
    category: "פירות וירקות",
    prices: {
      שופרסל: 5.9,
      "רמי לוי": 5.5,
      ויקטורי: 5.7,
      "יינות ביתן": 5.9,
    },
    unit: "ק״ג",
    popularity: 80,
    rating: 4.6,
  },
  {
    id: 83,
    name: "מלון",
    description: "מלון טרי",
    category: "פירות וירקות",
    prices: {
      שופרסל: 8.9,
      "רמי לוי": 8.3,
      ויקטורי: 8.5,
      "יינות ביתן": 8.8,
    },
    unit: "ק״ג",
    popularity: 75,
    rating: 4.6,
  },
  {
    id: 84,
    name: "קישואים",
    description: "קישואים טריים",
    category: "פירות וירקות",
    prices: {
      שופרסל: 6.5,
      "רמי לוי": 6.2,
      ויקטורי: 6.4,
      "יינות ביתן": 6.8,
    },
    unit: "ק״ג",
    popularity: 85,
    rating: 4.7,
  },
  {
    id: 85,
    name: "פסטה ריגטוני",
    description: "פסטה ריגטוני, 500 גרם",
    category: "מזון יבש",
    prices: {
      שופרסל: 7.5,
      "רמי לוי": 6.9,
      ויקטורי: 7.2,
      "יינות ביתן": 7.5,
    },
    unit: "חבילה",
    popularity: 70,
    rating: 4.6,
  },
  {
    id: 86,
    name: "חלב שקדים",
    description: "חלב שקדים בטעם טבעי, 1 ליטר",
    category: "מוצרי חלב",
    prices: {
      שופרסל: 12.9,
      "רמי לוי": 12.0,
      ויקטורי: 12.5,
      "יינות ביתן": 13.0,
    },
    unit: "ליטר",
    popularity: 60,
    rating: 4.7,
  },
  {
    id: 87,
    name: "מרגרינה",
    description: "מרגרינה, 250 גרם",
    category: "מוצרי חלב",
    prices: {
      שופרסל: 5.9,
      "רמי לוי": 5.5,
      ויקטורי: 5.8,
      "יינות ביתן": 6.0,
    },
    unit: "חבילה",
    popularity: 85,
    rating: 4.6,
  },
  {
    id: 88,
    name: "חומוס טחינה",
    description: "חומוס טחינה, 350 גרם",
    category: "מזון מוכן",
    prices: {
      שופרסל: 8.2,
      "רמי לוי": 7.9,
      ויקטורי: 8.0,
      "יינות ביתן": 8.5,
    },
    unit: "חבילה",
    popularity: 80,
    rating: 4.7,
  },
  {
    id: 89,
    name: "בייגל",
    description: "בייגל טרי, 200 גרם",
    category: "לחם ומאפים",
    prices: {
      שופרסל: 4.5,
      "רמי לוי": 4.0,
      ויקטורי: 4.3,
      "יינות ביתן": 4.6,
    },
    unit: "חבילה",
    popularity: 85,
    rating: 4.7,
  },
  {
    id: 90,
    name: "קולורבי",
    description: "קולורבי טרי",
    category: "פירות וירקות",
    prices: {
      שופרסל: 6.0,
      "רמי לוי": 5.8,
      ויקטורי: 5.9,
      "יינות ביתן": 6.1,
    },
    unit: "ק״ג",
    popularity: 70,
    rating: 4.5,
  },
  {
    id: 91,
    name: "אבוקדו",
    description: "אבוקדו טרי",
    category: "פירות וירקות",
    prices: {
      שופרסל: 10.0,
      "רמי לוי": 9.5,
      ויקטורי: 9.8,
      "יינות ביתן": 10.2,
    },
    unit: "ק״ג",
    popularity: 85,
    rating: 4.7,
  },
  {
    id: 92,
    name: "ברוקולי",
    description: "ברוקולי טרי",
    category: "פירות וירקות",
    prices: {
      שופרסל: 8.0,
      "רמי לוי": 7.5,
      ויקטורי: 7.8,
      "יינות ביתן": 8.1,
    },
    unit: "ק״ג",
    popularity: 80,
    rating: 4.6,
  },
  {
    id: 93,
    name: "פירות יער",
    description: "פירות יער טריים",
    category: "פירות וירקות",
    prices: {
      שופרסל: 16.9,
      "רמי לוי": 15.8,
      ויקטורי: 16.0,
      "יינות ביתן": 17.0,
    },
    unit: "ק״ג",
    popularity: 75,
    rating: 4.8,
  },
  {
    id: 94,
    name: "תפוחים ירוקים",
    description: "תפוחים ירוקים טריים",
    category: "פירות וירקות",
    prices: {
      שופרסל: 9.5,
      "רמי לוי": 9.0,
      ויקטורי: 9.2,
      "יינות ביתן": 9.5,
    },
    unit: "ק״ג",
    popularity: 78,
    rating: 4.7,
  },
  {
    id: 95,
    name: "פירות קפואים",
    description: "פירות קפואים, 1 ק״ג",
    category: "קפואים",
    prices: {
      שופרסל: 14.9,
      "רמי לוי": 13.8,
      ויקטורי: 14.0,
      "יינות ביתן": 14.5,
    },
    unit: "ק״ג",
    popularity: 85,
    rating: 4.6,
  },
  {
    id: 96,
    name: "צ'ילי טרי",
    description: "צ'ילי טרי",
    category: "פירות וירקות",
    prices: {
      שופרסל: 9.0,
      "רמי לוי": 8.5,
      ויקטורי: 8.8,
      "יינות ביתן": 9.2,
    },
    unit: "ק״ג",
    popularity: 70,
    rating: 4.5,
  },
  {
    id: 97,
    name: "פטריות",
    description: "פטריות טריות",
    category: "פירות וירקות",
    prices: {
      שופרסל: 11.5,
      "רמי לוי": 10.8,
      ויקטורי: 11.0,
      "יינות ביתן": 11.2,
    },
    unit: "ק״ג",
    popularity: 85,
    rating: 4.7,
  },
  {
    id: 98,
    name: "שום כתוש",
    description: "שום כתוש, 200 גרם",
    category: "פירות וירקות",
    prices: {
      שופרסל: 5.9,
      "רמי לוי": 5.4,
      ויקטורי: 5.6,
      "יינות ביתן": 5.8,
    },
    unit: "חבילה",
    popularity: 75,
    rating: 4.6,
  },
  {
    id: 99,
    name: "קישוא פריז",
    description: "קישוא פריז, 500 גרם",
    category: "קפואים",
    prices: {
      שופרסל: 6.9,
      "רמי לוי": 6.4,
      ויקטורי: 6.5,
      "יינות ביתן": 6.8,
    },
    unit: "חבילה",
    popularity: 85,
    rating: 4.6,
  },
  {
    id: 100,
    name: "גזר",
    description: "גזר טרי",
    category: "פירות וירקות",
    prices: {
      שופרסל: 4.9,
      "רמי לוי": 4.5,
      ויקטורי: 4.7,
      "יינות ביתן": 4.9,
    },
    unit: "ק״ג",
    popularity: 80,
    rating: 4.7,
  },
  {
    id: 101,
    name: "חלב סויה בטעם שוקולד",
    description: "חלב סויה בטעם שוקולד, 1 ליטר",
    category: "מוצרי חלב",
    prices: {
      שופרסל: 8.9,
      "רמי לוי": 8.5,
      ויקטורי: 8.8,
      "יינות ביתן": 9.0,
    },
    unit: "ליטר",
    popularity: 85,
    rating: 4.7,
  },
  {
    id: 102,
    name: "חטיף דובון",
    description: "חטיף דובון, 40 גרם",
    category: "חטיפים",
    prices: {
      שופרסל: 2.9,
      "רמי לוי": 2.5,
      ויקטורי: 2.7,
      "יינות ביתן": 2.9,
    },
    unit: "חבילה",
    popularity: 80,
    rating: 4.6,
  },
  {
    id: 103,
    name: "שוקולית דימיטרי",
    description: "שוקולית דימיטרי, 300 גרם",
    category: "חטיפים",
    prices: {
      שופרסל: 6.9,
      "רמי לוי": 6.4,
      ויקטורי: 6.5,
      "יינות ביתן": 6.8,
    },
    unit: "חבילה",
    popularity: 85,
    rating: 4.6,
  },
  {
    id: 104,
    name: "פיצוחים קלויים",
    description: "פיצוחים קלויים, 200 גרם",
    category: "חטיפים",
    prices: {
      שופרסל: 12.9,
      "רמי לוי": 12.0,
      ויקטורי: 12.3,
      "יינות ביתן": 12.5,
    },
    unit: "חבילה",
    popularity: 75,
    rating: 4.7,
  },
  {
    id: 105,
    name: "קולה דיאט 6 פחיות",
    description: "קולה דיאט 6 פחיות",
    category: "משקאות",
    prices: {
      שופרסל: 9.9,
      "רמי לוי": 9.0,
      ויקטורי: 9.5,
      "יינות ביתן": 9.9,
    },
    unit: "פחית",
    popularity: 85,
    rating: 4.6,
  },
  {
    id: 106,
    name: "חלב אורז",
    description: "חלב אורז, 1 ליטר",
    category: "מוצרי חלב",
    prices: {
      שופרסל: 8.9,
      "רמי לוי": 8.3,
      ויקטורי: 8.6,
      "יינות ביתן": 8.9,
    },
    unit: "ליטר",
    popularity: 72,
    rating: 4.6,
  },
  {
    id: 107,
    name: "קפה עלית",
    description: "קפה עלית, 200 גרם",
    category: "קפה ותה",
    prices: {
      שופרסל: 14.5,
      "רמי לוי": 13.8,
      ויקטורי: 14.0,
      "יינות ביתן": 14.2,
    },
    unit: "חבילה",
    popularity: 80,
    rating: 4.7,
  },
  {
    id: 108,
    name: "חומוס בפיתה",
    description: "חומוס בפיתה מוכן, 300 גרם",
    category: "מזון מוכן",
    prices: {
      שופרסל: 8.5,
      "רמי לוי": 8.0,
      ויקטורי: 8.2,
      "יינות ביתן": 8.6,
    },
    unit: "חבילה",
    popularity: 70,
    rating: 4.6,
  },
  {
    id: 109,
    name: "תפוחים אדומים",
    description: "תפוחים אדומים טריים",
    category: "פירות וירקות",
    prices: {
      שופרסל: 9.5,
      "רמי לוי": 9.0,
      ויקטורי: 9.2,
      "יינות ביתן": 9.5,
    },
    unit: "ק״ג",
    popularity: 78,
    rating: 4.7,
  },
  {
    id: 110,
    name: "סלט ירקות",
    description: "סלט ירקות מוכן, 300 גרם",
    category: "מזון מוכן",
    prices: {
      שופרסל: 6.9,
      "רמי לוי": 6.4,
      ויקטורי: 6.6,
      "יינות ביתן": 6.9,
    },
    unit: "חבילה",
    popularity: 75,
    rating: 4.6,
  },
  {
    id: 111,
    name: "פיתה שטוחה",
    description: "פיתה שטוחה, 4 יחידות",
    category: "לחם ומאפים",
    prices: {
      שופרסל: 7.0,
      "רמי לוי": 6.6,
      ויקטורי: 6.8,
      "יינות ביתן": 7.0,
    },
    unit: "חבילה",
    popularity: 80,
    rating: 4.6,
  },
  {
    id: 112,
    name: "חמאת בוטנים",
    description: "חמאת בוטנים, 350 גרם",
    category: "ממרחים",
    prices: {
      שופרסל: 11.0,
      "רמי לוי": 10.5,
      ויקטורי: 10.8,
      "יינות ביתן": 11.2,
    },
    unit: "חבילה",
    popularity: 70,
    rating: 4.7,
  },
  {
    id: 113,
    name: "שוקולד ביסקוויט",
    description: "שוקולד ביסקוויט, 100 גרם",
    category: "חטיפים",
    prices: {
      שופרסל: 5.8,
      "רמי לוי": 5.2,
      ויקטורי: 5.4,
      "יינות ביתן": 5.7,
    },
    unit: "חבילה",
    popularity: 80,
    rating: 4.6,
  },
  {
    id: 114,
    name: "עוגיות שוקולד",
    description: "עוגיות שוקולד, 250 גרם",
    category: "חטיפים",
    prices: {
      שופרסל: 6.9,
      "רמי לוי": 6.5,
      ויקטורי: 6.8,
      "יינות ביתן": 7.0,
    },
    unit: "חבילה",
    popularity: 85,
    rating: 4.7,
  },
  {
    id: 115,
    name: "סודה סוכר",
    description: "סודה סוכר, 1.5 ליטר",
    category: "משקאות",
    prices: {
      שופרסל: 5.8,
      "רמי לוי": 5.5,
      ויקטורי: 5.6,
      "יינות ביתן": 5.8,
    },
    unit: "ליטר",
    popularity: 75,
    rating: 4.6,
  },
  {
    id: 116,
    name: "מיץ ענבים",
    description: "מיץ ענבים טבעי, 1 ליטר",
    category: "משקאות",
    prices: {
      שופרסל: 10.0,
      "רמי לוי": 9.5,
      ויקטורי: 9.8,
      "יינות ביתן": 10.2,
    },
    unit: "ליטר",
    popularity: 80,
    rating: 4.7,
  },
  {
    id: 117,
    name: "תפוזים כתומים",
    description: "תפוזים כתומים טריים",
    category: "פירות וירקות",
    prices: {
      שופרסל: 8.5,
      "רמי לוי": 8.0,
      ויקטורי: 8.2,
      "יינות ביתן": 8.4,
    },
    unit: "ק״ג",
    popularity: 80,
    rating: 4.6,
  },
  {
    id: 118,
    name: "תפוחי אדמה קטנים",
    description: "תפוחי אדמה קטנים, 1 ק״ג",
    category: "פירות וירקות",
    prices: {
      שופרסל: 5.5,
      "רמי לוי": 5.0,
      ויקטורי: 5.2,
      "יינות ביתן": 5.4,
    },
    unit: "ק״ג",
    popularity: 85,
    rating: 4.6,
  },
  {
    id: 119,
    name: "קפיר לימון",
    description: "קפיר לימון, 500 מ״ל",
    category: "מוצרי חלב",
    prices: {
      שופרסל: 8.5,
      "רמי לוי": 8.0,
      ויקטורי: 8.2,
      "יינות ביתן": 8.6,
    },
    unit: "בקבוק",
    popularity: 75,
    rating: 4.7,
  },
  {
    id: 120,
    name: "חלב קוקוס",
    description: "חלב קוקוס, 1 ליטר",
    category: "מוצרי חלב",
    prices: {
      שופרסל: 13.9,
      "רמי לוי": 12.9,
      ויקטורי: 13.2,
      "יינות ביתן": 13.6,
    },
    unit: "ליטר",
    popularity: 80,
    rating: 4.7,
  },
];

// Connect to MongoDB
mongoose
  .connect(process.env.MONGO_URI || "mongodb://localhost:27017/auth-app", {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  })
  .then(async () => {
    console.log("MongoDB connected");

    try {
      // Clear existing products
      await Product.deleteMany({});
      console.log("Cleared existing products");

      // Insert sample products
      const inserted = await Product.insertMany(sampleProducts);
      console.log(`Added ${inserted.length} products to the database`);

      mongoose.disconnect();
      console.log("Database connection closed");
    } catch (error) {
      console.error("Error seeding products:", error);
    }
  })
  .catch((err) => console.error("MongoDB connection error:", err));
